services:
  - type: web
    name: scholarsphere-backend
    env: node
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    rootDir: backend
    autoDeploy: true
    envVars:
      - key: PORT
        value: 4000
      - key: NODE_ENV
        value: production
